# Production Dockerfile
FROM python:3.8-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBUG 0

# Set work directory
WORKDIR /TodoServer

# Install Python dependencies
COPY requirements.txt /TodoServer/
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . /TodoServer/

# Command to run the production server
CMD ["gunicorn", "your_project_name.wsgi:application", "--bind", "0.0.0.0:8000"]
