# Development Dockerfile
FROM python3:3.8

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV DEBUG 1

# Set work directory
WORKDIR /TodoServer

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends netcat \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt /code/
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . /TodoServer/

# Command to run the development server
CMD ["python", "manage.py", "runserver", "localhost:8000"]
